name: reno_music
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animations: ^2.0.0
  window_manager: ^0.3.8
  dropdown_button2: ^2.3.0
  flutter_svg: ^2.0.0
  sentry_flutter: ^7.18.0
  freezed_annotation: ^2.4.0
#  just_audio:
  cached_network_image: ^3.3.0
#  just_audio_background:
  go_router: ^13.2.2
  intl: ^0.19.0
  json_annotation: ^4.8.0
  flutter_spinkit: ^5.2.0
  modal_bottom_sheet: ^3.0.0-pre
  palette_generator:
  responsive_builder: ^0.7.0
#  riverpod_infinite_scroll: ^1.0.0
  infinite_scroll_pagination: ^3.2.0
  flutter_riverpod: ^2.4.0
  pretty_dio_logger: ^1.0.0
  flutter_secure_storage: ^9.0.0
  retrofit: ^4.1.0
  dio: ^5.4.0
  string_capitalize: ^0.0.10
  sliver_tools: ^0.2.0
  hooks_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  flutter_animate: ^4.2.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.0
  riverpod_lint: ^2.3.3
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
  test: ^1.24.9
  riverpod_generator: ^2.4.0
  go_router_builder: any
  build_runner: any
  build_verify: any
  flutter_lints: ^3.0.0
  riverpod_annotation: ^2.3.5


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_intl:
  enabled: true























